# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "65057e4200deff90b71e14f11f2c5da3"
name = "nebula-app"
handle = "nebula-app"
application_url = "https://nebula-app-snhd.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_script_tags,write_script_tags,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://nebula-app-snhd.onrender.com/auth/callback",
  "https://nebula-app-snhd.onrender.com/auth/shopify/callback",
  "https://nebula-app-snhd.onrender.com/api/auth/callback"
]

[pos]
embedded = false
